language: generic
sudo: false
before_install:
  # Install emacs (24.3) and cask
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  # Make sure emacs is installed
  - emacs --version
  # Install dependencies
  - cask
script:
  - cask exec ecukes features


