# Taken and modified from:
# https://github.com/rejeep/drag-stuff.el/blob/master/.travis.yml

language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.4-travis
script:
  - emacs --version
  - cask exec ecukes features


